# Generated by Django 2.2.14 on 2022-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preco')),
                ('estoque', models.IntegerField(verbose_name='estoque inteiro apenas')),
            ],
        ),
    ]
