# Generated by Django 3.2.12 on 2022-04-08 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
